services:
  front:
    image: node:22-alpine
    volumes:
      - ./front:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run dev -- -o
    network_mode: host

  api:
    image: node:22-alpine
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - 3001:3001
    command: npm run dev
    network_mode: host

  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=app
      - POSTGRES_USER=app
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    network_mode: host

  adminer:
    image: adminer
    ports:
      - 8080:8080
    network_mode: host

volumes:
  postgres:
