services:
  front:
    image: node:22-alpine
    volumes:
      - ./front:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run dev -- -o
    network_mode: host

  api:
    image: node:22-alpine
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - 3001:3001
    command: npm run dev
    network_mode: host
